job_titles:
  - List of job titles considered
ideal_job_description: >
  - Short description of the ideal job of the user

technical_skills:
  - Dictionnary of technical skills with proficiency levels

general skills: 
  - Dictionnary with limited keys and proficiency levels
    - Expression (oral and written): Excellent
    - Project management: Good
    - Modeling complexity: Excellent
    - Business acumen: Good

education_level: highest education level in relevant field or honest equivalent number of years of study

experience: Multiple choice of relevant years of experience ranges
  - 0-2 years
  - 3-5 years
  - 6-10 years
  - 10+ years